backend/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      member do
        post :clone
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :stores do
      member do
        post :set_default
      end
    end

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: 'option_values#destroy', as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: 'product_properties#destroy', as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        get :store
        put :set_store
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: 'orders/customer_details'
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    get '/return_authorizations', to: 'return_index#return_authorizations', as: :return_authorizations
    get '/customer_returns', to: 'return_index#customer_returns', as: :customer_returns

    resource :general_settings do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show]

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types
    resources :refund_reasons, except: :show
    resources :return_authorization_reasons, except: :show

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :store_credit_categories
    resources :tax_rates
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end
    resources :roles

    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
      end
      resources :store_credits
    end
  end

  spree_path = Rails.application.routes.url_helpers.try(:spree_path, trailing_slash: true) || '/'
  get Spree.admin_path, to: redirect((spree_path + Spree.admin_path + '/orders').gsub('//', '/')), as: :admin
end

backend/app/controllers/spree/admin/payment_methods_controller.rb
module Spree
  module Admin
    class PaymentMethodsController < ResourceController
      skip_before_action :load_resource, only: :create
      before_action :load_data
      before_action :validate_payment_method_provider, only: :create

      respond_to :html

      def create
        @payment_method = params[:payment_method].delete(:type).constantize.new(payment_method_params)
        @object = @payment_method
        invoke_callbacks(:create, :before)
        if @payment_method.save
          invoke_callbacks(:create, :after)
          flash[:success] = Spree.t(:successfully_created, resource: Spree.t(:payment_method))
          redirect_to edit_admin_payment_method_path(@payment_method)
        else
          invoke_callbacks(:create, :fails)
          respond_with(@payment_method)
        end
      end

      def update
        invoke_callbacks(:update, :before)
        payment_method_type = params[:payment_method].delete(:type)
        if @payment_method['type'].to_s != payment_method_type
          @payment_method.update_columns(
            type: payment_method_type,
            updated_at: Time.current
          )
          @payment_method = PaymentMethod.find(params[:id])
        end

        attributes = payment_method_params.merge(preferences_params)
        attributes.each do |k, _v|
          attributes.delete(k) if k.include?('password') && attributes[k].blank?
        end

        if @payment_method.update(attributes)
          invoke_callbacks(:update, :after)
          flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:payment_method))
          redirect_to edit_admin_payment_method_path(@payment_method)
        else
          invoke_callbacks(:update, :fails)
          respond_with(@payment_method)
        end
      end

      private

      def collection
        @collection = super.order(position: :asc)
      end

      def load_data
        @providers = Gateway.providers.sort_by(&:name)
      end

      def validate_payment_method_provider
        valid_payment_methods = Rails.application.config.spree.payment_methods.map(&:to_s)
        unless valid_payment_methods.include?(params[:payment_method][:type])
          flash[:error] = Spree.t(:invalid_payment_provider)
          redirect_to new_admin_payment_method_path
        end
      end

      def payment_method_params
        params.require(:payment_method).permit!
      end

      def preferences_params
        key = ActiveModel::Naming.param_key(@payment_method)
        return {} unless params.key? key

        params.require(key).permit!
      end
    end
  end
end

backend/app/views/spree/admin/payment_methods/_form.html.erb
<div data-hook="admin_payment_method_form_fields">

  <div data-hook="payment_method" class="row">

    <div class="col-12 col-md-4">
      <div id="preference-settings" data-hook class="form-group">
        <%= f.label :type, Spree.t(:provider) %>
        <%= collection_select(:payment_method, :type, @providers, :to_s, :name, {}, {id: 'gtwy-type', class: 'select2'}) %>

        <% unless @object.new_record? %>
          <%= preference_fields(@object, f) %>

          <% if @object.respond_to?(:preferences) %>
            <div id="gateway-settings-warning" class="info warning"><%= Spree.t(:provider_settings_warning) %></div>
          <% end %>
        <% end %>
      </div>
      <div data-hook="display" class="form-group">
        <%= label_tag :payment_method_display_on, Spree.t(:display) %>
        <%= select(:payment_method, :display_on, Spree::PaymentMethod::DISPLAY.collect { |display| [Spree.t(display), display.to_s] }, {}, {class: 'select2'}) %>
      </div>
      <div data-hook="auto_capture" class="form-group">
        <%= label_tag :payment_method_auto_capture, Spree.t(:auto_capture) %>
        <%= select(:payment_method, :auto_capture, [["#{Spree.t(:use_app_default)} (#{Spree::Config[:auto_capture]})", ''], [Spree.t(:say_yes), true], [Spree.t(:say_no), false]], {}, {class: 'select2'}) %>
      </div>
      <div data-hook="active" class="form-group">
        <strong><%= Spree.t(:active) %></strong>
        <div class="radio my-2">
          <%= label_tag :payment_method_active_true do %>
            <%= radio_button :payment_method, :active, true %>
            <%= Spree.t(:say_yes) %>
          <% end %>
        </div>

        <div class="radio my-2">
          <%= label_tag :payment_method_active_false do %>
            <%= radio_button :payment_method, :active, false %>
            <%= Spree.t(:say_no) %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-8">
      <%= field_container :payment_method, :name, class: ['form-group'], 'data-hook' => 'name' do %>
        <%= label_tag :payment_method_name, Spree.t(:name) %>
        <%= text_field :payment_method, :name, class: 'form-control' %>
        <%= error_message_on :payment_method, :name %>
      <% end %>
      <%= field_container :payment_method, :description, class: ['form-group'], 'data-hook' => 'description' do %>
        <%= label_tag :payment_method_description, Spree.t(:description) %>
        <%= text_area :payment_method, :description, { cols: 60, rows: 6, class: 'form-control' } %>
      <% end %>
    </div>
  </div>
</div>

backend/app/views/spree/admin/payment_methods/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:payment_methods), spree.admin_payment_methods_url %> /
  <%= @payment_method.name %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @payment_method } %>

<%= form_for @payment_method, url: admin_payment_method_path(@payment_method) do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

backend/app/views/spree/admin/payment_methods/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::PaymentMethod) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_payment_method), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_payment_methods_link' %>
<% end if can? :create, Spree::PaymentMethod %>

<% if @payment_methods.any? %>
  <table class="table sortable" id='listing_payment_methods' data-hook data-sortable-link="<%= update_positions_admin_payment_methods_url %>">
    <thead>
      <tr data-hook="admin_payment_methods_index_headers">
        <th></th>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:provider) %></th>
        <th class="text-center"><%= Spree.t(:display) %></th>
        <th class="text-center"><%= Spree.t(:active) %></th>
        <th data-hook="admin_payment_methods_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @payment_methods.each do |method|%>
        <tr id="<%= spree_dom_id method %>" data-hook="admin_payment_methods_index_rows">
          <td class="move-handle text-center">
            <% if can?(:edit, method) %>
              <span class="icon icon-move handle"></span>
            <% end %>
          </td>
          <td><%= method.name %></td>
          <td><%= method.type %></td>
          <td class="text-center"><%= Spree.t(method.display_on) %></td>
          <td class="text-center"><%= method.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td data-hook="admin_payment_methods_index_row_actions" class="actions actions-2 text-right">
            <%= link_to_edit(method, no_text: true) if can? :edit, method %>
            <%= link_to_delete(method, no_text: true) if can? :delete, method %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::PaymentMethod)) %>,
    <%= link_to(Spree.t(:add_one), new_object_url) if can? :create, Spree::PaymentMethod %>!
  </div>
<% end %>

backend/app/views/spree/admin/payment_methods/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:payment_methods), spree.admin_payment_methods_url %> /
  <%= Spree.t(:new_payment_method) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @payment_method } %>

<%= form_for @payment_method, url: collection_url do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>