backend/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      member do
        post :clone
      end
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :stores do
      member do
        post :set_default
      end
    end

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        post :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
    end

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: 'option_values#destroy', as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: 'product_properties#destroy', as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        get :store
        put :set_store
      end

      resources :state_changes, only: [:index]

      resource :customer, controller: 'orders/customer_details'
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end
    end

    get '/return_authorizations', to: 'return_index#return_authorizations', as: :return_authorizations
    get '/customer_returns', to: 'return_index#customer_returns', as: :customer_returns

    resource :general_settings do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show]

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types
    resources :refund_reasons, except: :show
    resources :return_authorization_reasons, except: :show

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, only: [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_items, only: [:create, :update, :destroy]
    resources :store_credit_categories
    resources :tax_rates
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end
    resources :roles

    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
      end
      resources :store_credits
    end
  end

  spree_path = Rails.application.routes.url_helpers.try(:spree_path, trailing_slash: true) || '/'
  get Spree.admin_path, to: redirect((spree_path + Spree.admin_path + '/orders').gsub('//', '/')), as: :admin
end

backend/app/controllers/spree/admin/adjustments_controller.rb
module Spree
  module Admin
    class AdjustmentsController < ResourceController
      belongs_to 'spree/order', find_by: :number

      create.after :update_totals
      destroy.after :update_totals
      update.after :update_totals

      skip_before_action :load_resource, only: [:toggle_state, :edit, :update, :destroy]

      before_action :find_adjustment, only: [:destroy, :edit, :update]

      def index
        @adjustments = @order.all_adjustments.eligible.order(created_at: :asc)
      end

      private

      def find_adjustment
        # Need to assign to @object here to keep ResourceController happy
        @adjustment = @object = parent.all_adjustments.find(params[:id])
      end

      def update_totals
        @order.reload.update_with_updater!
      end

      # Override method used to create a new instance to correctly
      # associate adjustment with order
      def build_resource
        parent.adjustments.build(order: parent)
      end
    end
  end
end

backend/app/helpers/spree/admin/adjustments_helper.rb
module Spree
  module Admin
    module AdjustmentsHelper
      def display_adjustable(adjustable)
        case adjustable
        when Spree::LineItem
          display_line_item(adjustable)
        when Spree::Shipment
          display_shipment(adjustable)
        when Spree::Order
          display_order(adjustable)
        end
      end

      private

      def display_line_item(line_item)
        variant = line_item.variant
        parts = []
        parts << variant.product.name
        parts << "(#{variant.options_text})" if variant.options_text.present?
        parts << line_item.display_total
        safe_join(parts, '<br />'.html_safe)
      end

      def display_shipment(shipment)
        "#{Spree.t(:shipment)} ##{shipment.number}<br>#{shipment.display_cost}".html_safe
      end

      def display_order(_order)
        Spree.t(:order)
      end
    end
  end
end

backend/app/views/spree/admin/adjustments/_adjustment.html.erb
<%
  @edit_url = edit_admin_order_adjustment_path(@order, adjustment)
  @delete_url = admin_order_adjustment_path(@order, adjustment)
%>

<tr id="<%= spree_dom_id(adjustment) %>" class="<%= adjustment.eligible? ? 'eligible' : 'ineligible' %>" data-hook="adjustment_row">
  <td>
    <%= display_adjustable(adjustment.adjustable) %>
  </td>
  <td>
    <%= adjustment.label %>
  </td>
  <td class="text-center">
    <%= adjustment.display_amount.to_html %>
  </td>
  <td class="text-center">
    <span class="badge badge-<%= adjustment.state %>">
      <%= adjustment.state %>
    </span>
  </td>
  <td class="actions actions-2 text-center">
    <% if adjustment.open? %>
      <%= link_to_edit(adjustment, no_text: true) if can?(:edit, adjustment) %>
      <%= link_to_delete(adjustment, no_text: true) if can?(:delete, adjustment) %>
    <% end %>
  </td>
</tr>

backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb
<div class="card-header">
  <h3 class="card-title mb-0 h5"><%= Spree.t(:order_adjustments) %></h3>
</div>

<table class="table table-bordered adjustments" data-hook="adjustments">
  <thead data-hook="adjustmment_head">
    <tr>
      <th><%= Spree.t(:adjustable) %></th>
      <th><%= Spree.t(:description) %></th>
      <th class="text-center"><%= Spree.t(:amount) %></th>
      <th class="text-center"><%= Spree.t(:status) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "adjustment", collection: @adjustments %>
  </tbody>
</table>

<% if can?(:edit, Spree::Adjustment) %>
  <div class="card-footer">
    <div class="row text-center pb-0">
      <div class="col-12 col-lg-6">
        <%= button_to Spree.t(:open_all_adjustments), open_adjustments_admin_order_path(@order), method: :get, class: "btn btn-success" %>
      </div>
      <div class="col-12 col-lg-6">
        <%= button_to Spree.t(:close_all_adjustments), close_adjustments_admin_order_path(@order), method: :get, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

backend/app/views/spree/admin/adjustments/_form.html.erb
<div data-hook="admin_adjustment_form_fields">
  <%= f.field_container :amount, class: ['form-group'] do %>
    <%= f.label :amount, raw(Spree.t(:amount) + content_tag(:span, " *", class: "required")) %>
    <%= text_field :adjustment, :amount, class: 'form-control' %>
    <%= f.error_message_on :amount %>
  <% end %>
  <%= f.field_container :label, class: ['form-group'] do %>
    <%= f.label :label, raw(Spree.t(:description) + content_tag(:span, " *", class: "required")) %>
    <%= text_field :adjustment, :label, class: 'form-control' %>
    <%= f.error_message_on :label %>
  <% end %>
</div>

backend/app/views/spree/admin/adjustments/edit.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :adjustments } %>

<% content_for :page_title do %>
  / <%= Spree.t(:edit) %> <%= Spree.t(:adjustment) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @adjustment } %>

<%= form_for @adjustment, url: admin_order_adjustment_path(@order, @adjustment), method: :put do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t(:continue), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_order_adjustments_url(@order), icon: 'delete' %>
    </div>
  </fieldset>
<% end %>

backend/app/views/spree/admin/adjustments/index.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :adjustments} %>

<% content_for :page_title do %>
   / <%= plural_resource_name(Spree::Adjustment) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:new_adjustment), new_admin_order_adjustment_url(@order), class: "btn-success", icon: 'add') if can? :create, Spree::Adjustment %>
<% end %>

<% if @adjustments.present? %>
  <div class="card mb-3">
    <%= render partial: 'adjustments_table' %>
  </div>
<% else %>
  <div class="alert alert-warning">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Adjustment)) %>
  </div>
<% end %>

<% if @order.can_add_coupon? %>
  <div class="card bg-light mb-3" data-hook="adjustments_new_coupon_code">
    <div class="card-body">
      <div class="form-group">
        <%= text_field_tag "coupon_code", "", placeholder: Spree.t(:coupon_code), class: "form-control" %>
      </div>
      <%= button Spree.t(:add_coupon_code), 'plus', 'submit', id: "add_coupon_code" %>
    </div>
  </div>
<% end %>

<%= javascript_tag do %>
  var order_number = '<%= @order.number %>';
<% end %>

<%= render partial: 'spree/admin/shared/order_summary' %>

backend/app/views/spree/admin/adjustments/new.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :adjustments } %>

<% content_for :page_title do %>
  / <%= Spree.t(:new_adjustment) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @adjustment } %>

<%= form_for @adjustment, url: admin_order_adjustments_path do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t(:continue), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_order_adjustments_url(@order), icon: 'delete' %>
    </div>
  </fieldset>
<% end %>